# Site settings
baseURL = "https://beingwith.netlify.app/"
languageCode = "en-us"
title = "Being with Tom"
theme = "forty"
publishDir = "public"
# Enter your disqus shortname to enable comments
disqusShortname = "beingtogether"

enableEmoji = true

[privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = true
    useSessionStorage = true
  [privacy.instagram]
    disable = false
    simple = false
  [privacy.twitter]
    disable = false
    enableDNT = true
    simple = false
  [privacy.vimeo]
    disable = false
    enableDNT = true
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = true


[params]
  # You can use Markdown syntax for urls [text](//url.to/source)
  # To create multi-line text in strings use the """example Text""" format
  #
  # All icons using Fontawesome's icon font. Look at fontawesome.io/icons
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # Provide your metadata here.
  name = "Being with Tom"
  description = "Your description"

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []
  favicon    = "favicon.ico"

  # Just a custom image variable, please define it in .md files for content.
  image = ""

  # 404 error customization
  [params.error404]
    heading = "Page couldn't be found"
    text = "Please visit [this page](/)"

  # Navigation Section
  [params.navigation]
    title = "Being"
    subtitle = "With Tom"
    menu = "Menu"
    # Optional logo as brand stored in img/
    # logo = "logo.png"

    [[params.navigation.links]]
      name = "Home"
      url = "#"

    [[params.navigation.links]]
      name = "Generic Blog"
      url = "generic"

    [[params.navigation.button1]]
      name = "Log In"
      url = "admin"

    # Add custom links here by uncommenting code below. To remove links just delete
    # the [[params.navigation.links]] map associated with that link. Copy and paste
    # code below if you need more links. Buttons work in the same way.
    # [[params.navigation.links]]
    #    name = "NameOfLink"
    #    url = "UrlOfLink"


  # Banner section
  [params.banner]
    # To change the background image on the homepage banner, replace 'banner.jpg' in
    # the 'static/img' folder.
    title = "Being with Tom"
    subtitle = "The philosophers have only interpreted the world, in various ways: the point, however, is to change it.... - Karl Marx"
    buttonText = "Get Started"

  # Tiles Section
  [params.tiles]
    enable = true
    # Display your showcases here.

    [[params.tiles.showcase]]
      title = "Art"
      subtitle = "Art is always and everywhere the secret confession, and at the same time the immortal movement of its time. - M."
      image = "mirrorfield.jpg"
      url = "art"

    [[params.tiles.showcase]]
      title = "Philosophy"
      subtitle = "As long as I breath, I hope. As long I will breath, I will fight for the future, this radiant future, in which man, strong and beautiful, will becomes master of the the flowing stream of his history and will direct it towrads the unlimited horizens of beauty joy and happiness! - T."
      image = "revolution.jpg"
      url = "philosophy"

    [[params.tiles.showcase]]
      title = "Poetry"
      subtitle = "Language is the house of Being. In its home man dwells. Those who think and those who create with words are the guardians of this home. - H."
      image = "redsun.jpg"
      url = "poetry"

    [[params.tiles.showcase]]
      title = "Music"
      subtitle = "Music is the mirror of reality. - M."
      image = "octopuscar.jpg"
      url = "music"

    [[params.tiles.showcase]]
      title = "Film"
      subtitle = "Even the most perfect reproduction of a work of art is lacking in one element: its presence in time and space, its unique existence at the place where it happens to be. - B."
      image = "gears.jpg"
      url = "film"

    [[params.tiles.showcase]]
      title = "Life"
      subtitle = "We should never let our fears or the expectations of others set the frontiers of our destiny. - H."
      image = "caveman.jpg"
      url = "life"
    # You can make more showcases by copy and pasting the code above

  [params.blog]
    # All blogs defined in their own files. You can find example blogs
    # at 'exampleSite/content/blogs'. Copy the 'blogs' folder into the 'content' directory
    # at the root of this Hugo site.
    # For more informtion take a look at the README.
    # To add more blogs just copy and paste the code.

  # Section Type Two
  [params.two]
    enable = true
    title = "Let us break our chains!"
    subtitle = "Only in community with others has each individual the means of cultivating his gifts in all directions; only in the community, therefore, is personal freedom possible."
    buttonText = "Revolution"
    url = "blogs"


  # Contact section
  [params.contact]
    enable = true
    buttonSend = "Send message"
    buttonClear = "Clear"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below and uncomment
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    formEmail = "tom.guimberteau@gmail.com"

    # Contact Section
    # You can add multiple emails, phone numbers, or addresses
    # by copying the corresponding map with frontmatter code.
    [[params.contact.email]]
    title = "Email"
    email = "tom.guimberteau@gmail.com"

    [[params.contact.phone]]
    title = "Phone"
    phone = "+33 07 77 86 72 13"

    [[params.contact.address]]
    title = "Based In"
    city = "Strasbourg, 67000"
    country = "France"

  # Footer section
  [params.footer]
    enable = true
    copyright = "Tom Guimberteau"

    # Uses font awesome icons
    [[params.footer.social]]
      icon = "fa-twitter"
      url= "https://www.twitter.com/tomguim"
      label = "Twitter"

    [[params.footer.social]]
      icon = "fa-facebook"
      url= "https://www.facebook.com/tomguim"
      label = "Facebook"

    [[params.footer.social]]
      icon = "fa-instagram"
      url= "https://www.instagram.com/tomguim"
      label = "Instagram"

    [[params.footer.social]]
      icon = "fa-github"
      url= "https://www.github.com/tomguim"
      label = "GitHub"
